title: Crest Filecoin
description: Add the Crest documents to Filecoin
type: object
documents: []
properties:
  title:
    title: Title
    type: string
eventOptions:
  name: title
  events:
    - hourly
    - daily
    - weekly
