title: IPFS/Filecoin Batch Uploader
description: This Add-On allows you to upload large sets of documents in scheduled batches to the IPFS/Filecoin networks for long term preservation. Read about [our efforts](https://www.muckrock.com/news/archives/2024/sep/11/featured-add-on-push-to-ipfs-filecoin/) to preserve at risk documents with the help of the Filecoin Foundation for the Decentralized Web. 
type: object
documents: []
properties:
  project_id:
    title: Project ID
    type: integer
    description: Project ID of the project of documents you would like to upload in bulk. 
  batch_size:
    title: Batch size
    type: integer
    description: The number of documents you would like to upload during each run, higher numbers tend to increase failure rates.
    default: 25
required:
  - project_id
  - batch_size
eventOptions:
  name: title
  events:
    - hourly
    - daily
    - weekly
